development:
  adapter: postgresql
  encoding: unicode
  database: dadosabertos_development
  pool: 5
  username: dadosabertos
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: dadosabertos_test
  pool: 5
  username: dadosabertos
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: dadosabertos_production
  pool: 5
  username: dadosabertos
  password: password
